### PR TITLE
Provide option to `stop`, `warn` or `log` when pull/checkout fails

### LINKED ISSUE #9: investigate `load_pkgs(git_pull=TRUE)`
Find out the behavior if:
* the branch has uncommitted changes
* the branch has staged changes
* the branch has committed changes but not push to remote

### Refine:  
- [x] https://github.com/donyunardi/multiloadr/issues/20
- [ ] check if there's uncommitted changes. If there is, do not do git pull. Just load the branch.

### PR DESCRIPTION
**Pull request by vedhav**
Closes #9 

Changes:
The `load_pkgs` now checks for the status of the pull/checkout and log this for the user.
The user can choose if they need an `error`, `warning`, or `message` logged when git failure occurs. The default is `warning`.
This can also be set using an option in their `.Rprofile` using:
```r
options('multiloadr.load.verbose' = 'error') # stop with an error
options('multiloadr.load.verbose' = 'warning') # show a warning => default
options('multiloadr.load.verbose' = 'message') # show a message
```

### CODE REVIEW

**Comment by vedhav** [comment]
Hey @donyunardi
Looks like the CI failed because there was an error installing `httpuv` and `shiny` in the `Install dependencies` step. [I triggered the check](https://github.com/vedhav/multiloadr/pull/1) by creating a PR on the fork and it was successful. However, I think we can use ~`ubuntu-latest`~ `ubuntu-20.04` (the release version of ubuntu does not seem to install R release version properly) instead of `macos-latest` for the CI along with R `release` instead of `4.2.2`.

**Comment by vedhav** [comment]
Hopefully, you like the CI changes I proposed I was able to implement them (after a few tries as always 😆). I checked the CI on the fork and it seems to work now, runs faster too 😉
Screenshot 2023-12-09 at 3 04 45 PM

File: R/load_pkgs.R [hunk 1]
```diff
@@ -78,31 +86,50 @@ load_pkgs <- function(branch_name = NULL, git_pull = FALSE, from_commit = list()
...
+              pkg, "\033[0m\n"
+            )
+            if (load_verbose == "error") {
+              stop(message)
+            } else if (load_verbose == "warning") {
+              warning(message)
+            } else if (load_verbose != "silent") {
+              cat(message)
+            }
+          }
```
Comment (donyunardi) [inline R/load_pkgs.R]:
```suggestion
            switch(load_verbose,
              error = stop(message),
              warning = warning(message, immediate. = TRUE),
              silent = invisible(),
              cat(message)
            )
```

Make it prettier with `switch` statement?
Also setting `.immediate = TRUE` for warning so that the message shows immediately rather than at the end of execution.

File: R/load_pkgs.R [hunk 2]
```diff
@@ -78,31 +86,50 @@ load_pkgs <- function(branch_name = NULL, git_pull = FALSE, from_commit = list()
...
             "cd",
             args = c(path, paste("&& git checkout", branch)),
             stdout = FALSE,
             stderr = FALSE
           )
+          if (checkout_error) {
+            message <- paste(
+              "\033[0;91m`git checkout` failed.",
+              "Please check your local changes for\033[0;94m",
+              pkg, "\033[0m\n"
```
Comment (donyunardi) [inline R/load_pkgs.R]:
```suggestion
            message <- paste(
              "\033[0;91mCan't switch to", branch, "branch for\033[0;94m",
              pkg, "\033[0m\n",
              " \033[0;91mPlease check your local changes. \033[0m"
            )
```

What do you think about making the message more user friendly by not mentioning `git checkout`?

File: R/load_pkgs.R [hunk 3]
```diff
@@ -134,12 +161,26 @@ load_pkgs <- function(branch_name = NULL, git_pull = FALSE, from_commit = list()
...
+            )
+            if (load_verbose == "error") {
+              stop(message)
+            } else if (load_verbose == "warning") {
+              warning(message)
+            } else if (load_verbose != "silent") {
+              cat(message)
+            }
+          }
```
Comment (donyunardi) [inline R/load_pkgs.R]: We can do the same strategy here:
* use switch statement
* make warning shows immediately
* make the message more user friendly

**Review by donyunardi — CHANGES_REQUESTED** [review]
Thanks so much for these improvements, @vedhav!
Just had small changes.
If you don't have time, I'd be more than happy to make the changes.

**Comment by donyunardi** [comment]
> Hopefully, you like the CI changes I proposed I

I do! Thank you!

File: R/load_pkgs.R (hunk 3 above)
Comment (vedhav) [reply R/load_pkgs.R]: Agreed, made the changes!
While we're at #45 let's also remember to create a nice utils for this `log_verbose` logic that we can use in multiple places.

**Review by donyunardi — APPROVED** [review]
LGTM!
